// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwcR12y2EYn8QsmqNJz-Xcyu-Rl5BU0EU',
    appId: '1:437137578071:web:1cfb1cdb9ba3ac8a64ab12',
    messagingSenderId: '437137578071',
    projectId: 'farm-space',
    authDomain: 'farm-space.firebaseapp.com',
    storageBucket: 'farm-space.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKFz7cbCVcU9AMaHBV9UawvLz8qRSL6Fs',
    appId: '1:437137578071:android:6a01b743be11e13764ab12',
    messagingSenderId: '437137578071',
    projectId: 'farm-space',
    storageBucket: 'farm-space.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDvImsiSrPLhmEtJ4zHu0MjLq87c1RmNvQ',
    appId: '1:437137578071:ios:d104737aad075a5364ab12',
    messagingSenderId: '437137578071',
    projectId: 'farm-space',
    storageBucket: 'farm-space.firebasestorage.app',
    iosBundleId: 'com.example.poultryguard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDvImsiSrPLhmEtJ4zHu0MjLq87c1RmNvQ',
    appId: '1:437137578071:ios:d104737aad075a5364ab12',
    messagingSenderId: '437137578071',
    projectId: 'farm-space',
    storageBucket: 'farm-space.firebasestorage.app',
    iosBundleId: 'com.example.poultryguard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwcR12y2EYn8QsmqNJz-Xcyu-Rl5BU0EU',
    appId: '1:437137578071:web:a948a8a0f3d88d2264ab12',
    messagingSenderId: '437137578071',
    projectId: 'farm-space',
    authDomain: 'farm-space.firebaseapp.com',
    storageBucket: 'farm-space.firebasestorage.app',
  );

}